import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import { createSwaggerSpec } from 'next-swagger-doc';
import dynamic from 'next/dynamic';
import 'swagger-ui-react/swagger-ui.css';

const SwaggerUI = dynamic(import('swagger-ui-react'), { ssr: false });

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ spec }) => {
  return (
    <div>
      <Head>
        <title>竞赛模块</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SwaggerUI spec={spec} />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const spec: Record<string, any> = createSwaggerSpec({
    definition: {
      openapi: '3.0.0',
      info: {
        title: '程序员之家竞赛模块',
        version: '1.0',
      },
    },
  });

  return {
    props: {
      spec,
    },
  };
};

export default Home